on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout repository"
      uses: actions/checkout@v3

    - name: "Login to Docker Hub"
      run: docker login --username ${{ secrets.USERNAME }} --password ${{ secrets.TOKEN }}

    - name: "Building Docker image"
      run: docker build -t ${{ secrets.USERNAME }}/taskimage .

    - name: "Pushing to Docker Hub"
      run: docker push ${{ secrets.USERNAME }}/taskimage